### ISSUE TITLE
可否支持自己的发言在右边显示？

### ISSUE THREAD

**Issue by BruceOuyang** [dcyuki/docsify-chat#1]
可否支持左右显示？

**Comment by xueelf** [comment]
已更新 v0.1.2，新增 myself 及 animation 选项 (ﾟ▽ﾟ*)

**Comment by BruceOuyang** [comment]
赞~ 👍🏻

**Comment by Funarp** [comment]
今天第一次用docsify，怎么会有这么奇怪的插件，好怪好喜欢╭(●｀∀´●)╯╰(●’◡’●)╮

**Comment by xueelf** [comment]
> 今天第一次用docsify，怎么会有这么奇怪的插件，好怪好喜欢╭(●｀∀´●)╯╰(●’◡’●)╮

诶嘿~ (◕ω＜)☆
