### ISSUE TITLE
title 可以每个面板自定义吗？

### ISSUE THREAD

**Issue by BruceOuyang** [dcyuki/docsify-chat#2]
现在的版本是所有聊天框公用一个 `title` 的，如果每个面板可以定制 `title`，那一定很棒

**Comment by xueelf** [comment]
已更新 v0.1.4，支持 title 重写，相关示例可查看 [Option](https://github.com/dcyuki/docsify-chat#title) (ﾟ▽ﾟ*)

**Comment by BruceOuyang** [comment]
辛苦啦，ヾ(◍°∇°◍)ﾉﾞ

我试用了一下 `<!-- title:xxx -->`，发现有些细节问题:

 `<!-- title:xxx -->` 必须紧挨着  `<!-- chat:start -->` 或  `<!-- chat:end -->` 中间不能有空行，否则会显示异常的。

例如：

**markdown** 
```
# Test docsify-chat custom title

<!-- chat:start -->

<!-- title:yuki's chat history -->

#### **kokkoro**

hello

#### **yuki**

hello world

<!-- chat:end -->
```

**效果图**
![image](https://user-images.githubusercontent.com/5382942/172529933-5527f65c-e28e-4228-a940-5ed10c470bea.png)

**Comment by xueelf** [comment]
sorry，这周收到的邮件比较多，刚看到这个 bug，已经修复啦，可以清理下 cdn 缓存重新查看 ヽ(•ω•ゞ)

**Comment by BruceOuyang** [comment]
完美了，؏؏☝ᖗ乛◡乛ᖘ☝؏؏
