### ISSUE TITLE
和KaTeX插件冲突

### ISSUE THREAD

**Issue by AntiO2** [dcyuki/docsify-chat#6]
和[docsify-katex](https://github.com/upupming/docsify-katex)冲突。

![image](https://github.com/xueelf/docsify-chat/assets/46259425/2a6f0b6b-83f0-4557-b9c3-318b8a8f2b75)

**Comment by xueelf** [comment]
排查了好久，先说一下结论，这并不是 bug。

我这边的模板解析是没有问题的，docsify-chat 的原理是通过 docsify 提供的 [hook](https://docsify.js.org/#/zh-cn/write-a-plugin?id=%e5%ae%8c%e6%95%b4%e5%8a%9f%e8%83%bd) 将 md 里的模板语法转换成了 html 结构，到目前为止的表现行为都是在预期中。

查阅 [docsify-katex](https://github.com/upupming/docsify-katex) 源码得知，该库是直接将 docsify 内置的 markdown [解析规则](https://docsify.js.org/#/zh-cn/markdown) 给修改了，这从而导致使用该插件后**会影响到整个 md 的渲染表现**，作为一个插件而言这种做法实在是太过于偏激...

而 docsify-chat 的灵感来自于 docsify-tabs，你可能会有疑问，为什么 docsify-tabs 没有出现样式的问题？这是因为我为了开发的便捷性，docsify-chat 中针对 html 的解析生成使用了大量的模板字符串，这使得字符串对开发者更具可读性，不过这样会让生成出的 html 字符会留出几个回车，但这原本应该是一个无关紧要的事。

![e99f940c4fda5396dfb91718d2ac25ba](https://github.com/xueelf/docsify-chat/assets/37479458/b8e5be44-5871-4e90-b8ea-61767af4707f)

但就是因为某处的一个无关紧要的回车，由于被修改了 markdown 解析规则，从而导致后续的 html 结构无法被正常渲染到页面。要解决的方法嘛，也有，就是...

![dd990839934053b63fc9764d625dd95c](https://github.com/xueelf/docsify-chat/assets/37479458/aa588c3a-a380-4985-ac03-30b112ecb3f5)

哦我的老伙计，这又臭又长的代码简直比隔壁苏珊太太的苹果派还要糟糕。

原因已经定位到了，我想想后面有没有一个优雅的解决方案，咱有点代码洁癖。ㄟ( ▔, ▔ )ㄏ

**Comment by xueelf** [comment]
已更新 v0.4.2，可以清除 cdn 缓存后重新查看页面。(。・ω・。)

总结，没有更好的办法，~~不情不愿的~~ 加了一个 `replace` 删除多余的空格以及换行符。虽然会产生一些微乎其微的性能损耗，不过保留了代码的可读性和可维护性。

**Comment by AntiO2** [comment]
已解决。太帅了👍
